/**
 * Пиксельные значки лаунчера — одна таблица на весь интерфейс.
 *
 * Приказ владельца 23.09.2026: «все иконки в лаунчере пиксельные, как
 * сообщение» и «либо Minecraft-штука, либо не используй вообще». Образец —
 * облачко сообщений в лобби: сетка 12×12, пиксели-прямоугольники, тёмный
 * ступенчатый контур, белая заливка и 1–2 тона. Где можно — предмет Minecraft
 * вместо абстрактного значка: часы, сундук, книга, картина, карта, пластинка,
 * барьер, блок травы, колокол, баннер.
 *
 * Рисунок задаётся только заливкой: тёмный контур в одну клетку вокруг
 * силуэта (соседи по четырём сторонам) достраивается сам — так контур всегда
 * сплошной и ступенчатый, как рамка в Minecraft.
 *
 * Буквы палитры (одна клетка = один символ):
 *   .  пусто (контур вокруг заливки дорисуется сам)
 *   _  пусто без контура (дырка: кольцо ключа, дужка замка)
 *   c  цвет текста (currentColor) — значки-действия: крестик, галочка, стрелки
 *   C  цвет текста на 55% — второй тон одноцветных значков (гардероб)
 *   k  тёмный контур внутри рисунка (стрелки часов, прорези)
 *   w s d n  белый, светло-, средне-, тёмно-серый
 *   g l      тёмно- и светло-зелёный
 *   r R p    красный, тёмно-красный, розовый блик
 *   y Y      золото и его тень
 *   o O      дерево и его тень
 *   b B      алмазно-голубой и синий
 *   v V      фиолетовый и его тень
 *   f        оранжевый (огонь, медь)
 *   t        бумага
 */

export const PX_COLORS: Record<string, string> = {
  k: '#1b1f1c',
  w: '#ffffff',
  s: '#c9d3cc',
  d: '#8b968f',
  n: '#4d5550',
  c: 'currentColor',
  C: 'currentColor',
  g: '#2f8f46',
  l: '#62d26f',
  r: '#e23a50',
  R: '#9b1f33',
  p: '#ffa3b3',
  y: '#f7c843',
  Y: '#c3841a',
  o: '#b07838',
  O: '#6e4520',
  b: '#86e0f7',
  B: '#2b8fc4',
  v: '#b77cf0',
  V: '#6f3fb0',
  f: '#ff8c2a',
  t: '#f1ddb0',
}

type Art = string[]
type Derived = { from: string; t: 'flipH' | 'flipV' | 'rot90' | 'rot180' | 'rot270' }

/* Рисунки. Каждый — 12 строк по 12 символов. */
const ART: Record<string, Art | Derived> = {
  /* ── Действия (цвет текста) ── */
  x: [
    '............',
    '............',
    '..cc....cc..',
    '..ccc..ccc..',
    '...cccccc...',
    '....cccc....',
    '....cccc....',
    '...cccccc...',
    '..ccc..ccc..',
    '..cc....cc..',
    '............',
    '............',
  ],
  check: [
    '............',
    '............',
    '.........cc.',
    '........ccc.',
    '.......ccc..',
    '.cc...ccc...',
    '.ccc.ccc....',
    '..ccccc.....',
    '...ccc......',
    '....c.......',
    '............',
    '............',
  ],
  'chev-r': [
    '............',
    '............',
    '....cc......',
    '....ccc.....',
    '.....ccc....',
    '......ccc...',
    '......ccc...',
    '.....ccc....',
    '....ccc.....',
    '....cc......',
    '............',
    '............',
  ],
  'chev-l': { from: 'chev-r', t: 'flipH' },
  'phone-hang': { from: 'phone', t: 'rot90' },
  'chev-d': { from: 'chev-r', t: 'rot90' },
  'chev-u': { from: 'chev-r', t: 'rot270' },
  plus: [
    '............',
    '............',
    '.....cc.....',
    '.....cc.....',
    '.....cc.....',
    '..cccccccc..',
    '..cccccccc..',
    '.....cc.....',
    '.....cc.....',
    '.....cc.....',
    '............',
    '............',
  ],
  minus: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '..cccccccc..',
    '..cccccccc..',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  'arrow-r': [
    '............',
    '............',
    '......c.....',
    '......cc....',
    '......ccc...',
    '.ccccccccc..',
    '.ccccccccc..',
    '......ccc...',
    '......cc....',
    '......c.....',
    '............',
    '............',
  ],
  'arrow-l': { from: 'arrow-r', t: 'flipH' },
  'arrow-dn': { from: 'arrow-r', t: 'rot90' },
  'arrow-up': { from: 'arrow-r', t: 'rot270' },
  dots: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '.cc..cc..cc.',
    '.cc..cc..cc.',
    '............',
    '............',
    '............',
    '............',
    '............',
  ],
  /* ── Одноцветные значки меню и выбора (правка владельца 24.09.2026) ──
     Цветные предметы (карандаш-золото, папка, сундук) в строке текстового
     меню читались как эмодзи. Здесь те же смыслы силуэтом в цвет текста:
     «c» — основной тон, «C» — второй, без контура. */
  'mo-gear': [
    '............',
    '.....cc.....',
    '..cc.cc.cc..',
    '..cccccccc..',
    '...cccccc...',
    '.cccc..cccc.',
    '.cccc..cccc.',
    '...cccccc...',
    '..cccccccc..',
    '..cc.cc.cc..',
    '.....cc.....',
    '............',
  ],
  'mo-pencil': [
    '............',
    '........CC..',
    '.......CCCC.',
    '......ccCC..',
    '.....cccc...',
    '....cccc....',
    '...cccc.....',
    '..cccc......',
    '..ccc.......',
    '..cc........',
    '............',
    '............',
  ],
  'mo-folder': [
    '............',
    '............',
    '.cccc.......',
    '.cccccccccc.',
    '.CCCCCCCCCC.',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '............',
    '............',
  ],
  'mo-trash': [
    '............',
    '....cccc....',
    '.cccccccccc.',
    '............',
    '..cccccccc..',
    '..cc.cc.cc..',
    '..cc.cc.cc..',
    '..cc.cc.cc..',
    '..cc.cc.cc..',
    '..cccccccc..',
    '............',
    '............',
  ],
  /* Иконка сборки: картина с горой и солнцем (меню «⋯» своей сборки, 24.09.2026). */
  'mo-image': [
    '............',
    '............',
    '.cccccccccc.',
    '.c........c.',
    '.c.....CC.c.',
    '.c.....CC.c.',
    '.c..c.....c.',
    '.c.ccc..c.c.',
    '.cccccccccc.',
    '.cccccccccc.',
    '............',
    '............',
  ],
  'mo-key': [
    '............',
    '............',
    '.cccc.......',
    'cc..cc......',
    'c....cccccc.',
    'c....cccccc.',
    'cc..cc..c.c.',
    '.cccc...c.c.',
    '........c...',
    '............',
    '............',
    '............',
  ],
  'mo-shield': [
    '............',
    '..ccccCCCC..',
    '..ccccCCCC..',
    '..ccccCCCC..',
    '..ccccCCCC..',
    '..ccccCCCC..',
    '..ccccCCCC..',
    '..ccccCCCC..',
    '...cccCCC...',
    '....ccCC....',
    '.....cC.....',
    '............',
  ],
  'mo-user': [
    '............',
    '....cccc....',
    '....cccc....',
    '....cccc....',
    '....cccc....',
    '............',
    '..cccccccc..',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '............',
    '............',
  ],
  'mo-bag': [
    '............',
    '....cccc....',
    '...c....c...',
    '...c....c...',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccccccc.',
    '............',
    '............',
  ],
  grip: [
    '............',
    '............',
    '...cc..cc...',
    '...cc..cc...',
    '............',
    '...cc..cc...',
    '...cc..cc...',
    '............',
    '...cc..cc...',
    '...cc..cc...',
    '............',
    '............',
  ],
  download: [
    '............',
    '.....cc.....',
    '.....cc.....',
    '.....cc.....',
    '..cccccccc..',
    '...cccccc...',
    '....cccc....',
    '.....cc.....',
    '............',
    '.c........c.',
    '.cccccccccc.',
    '............',
  ],
  upload: [
    '............',
    '.....cc.....',
    '....cccc....',
    '...cccccc...',
    '..cccccccc..',
    '.....cc.....',
    '.....cc.....',
    '.....cc.....',
    '............',
    '.c........c.',
    '.cccccccccc.',
    '............',
  ],
  restart: [
    '............',
    '...cccc..cc.',
    '..cccccc.cc.',
    '.cc....cccc.',
    '.cc...ccccc.',
    '.cc.........',
    '.cc.........',
    '.cc......cc.',
    '..cc....cc..',
    '..cccccccc..',
    '....cccc....',
    '............',
  ],
  reply: [
    '............',
    '............',
    '...c........',
    '..cc........',
    '.cccccccc...',
    '.ccccccccc..',
    '..cc....cc..',
    '...c....cc..',
    '........cc..',
    '........cc..',
    '............',
    '............',
  ],
  play: [
    '............',
    '............',
    '...cc.......',
    '...cccc.....',
    '...cccccc...',
    '...cccccccc.',
    '...cccccccc.',
    '...cccccc...',
    '...cccc.....',
    '...cc.......',
    '............',
    '............',
  ],
  pause: [
    '............',
    '............',
    '..ccc..ccc..',
    '..ccc..ccc..',
    '..ccc..ccc..',
    '..ccc..ccc..',
    '..ccc..ccc..',
    '..ccc..ccc..',
    '..ccc..ccc..',
    '..ccc..ccc..',
    '............',
    '............',
  ],
  'skip-fwd': [
    '............',
    '............',
    '.cc.....cc..',
    '.cccc...cc..',
    '.cccccc.cc..',
    '.cccccccccc.',
    '.cccccccccc.',
    '.cccccc.cc..',
    '.cccc...cc..',
    '.cc.....cc..',
    '............',
    '............',
  ],
  'skip-back': { from: 'skip-fwd', t: 'flipH' },
  grid: [
    '............',
    '.cccc..cccc.',
    '.cccc..cccc.',
    '.cccc..cccc.',
    '.cccc..cccc.',
    '............',
    '............',
    '.cccc..cccc.',
    '.cccc..cccc.',
    '.cccc..cccc.',
    '.cccc..cccc.',
    '............',
  ],
  list: [
    '............',
    '............',
    '.cc.ccccccc.',
    '.cc.ccccccc.',
    '............',
    '.cc.ccccccc.',
    '.cc.ccccccc.',
    '............',
    '.cc.ccccccc.',
    '.cc.ccccccc.',
    '............',
    '............',
  ],
  filter: [
    '............',
    '............',
    '.cccccccccc.',
    '.cccccccccc.',
    '..cccccccc..',
    '...cccccc...',
    '....cccc....',
    '....cccc....',
    '....cccc....',
    '....ccc.....',
    '............',
    '............',
  ],
  send: [
    '............',
    '.........cc.',
    '.......cccc.',
    '.....cccccc.',
    '...cccccccc.',
    '.ccccccccc..',
    '...ccccccc..',
    '.....cccc...',
    '.....ccc....',
    '.....cc.....',
    '.....c......',
    '............',
  ],
  ext: [
    '............',
    '......ccccc.',
    '.........cc.',
    '........ccc.',
    '.cccc..cc.c.',
    '.c....cc....',
    '.c...cc...c.',
    '.c........c.',
    '.c........c.',
    '.c........c.',
    '.cccccccccc.',
    '............',
  ],
  power: [
    '............',
    '.....cc.....',
    '..c..cc..c..',
    '.cc..cc..cc.',
    '.c...cc...c.',
    '.c...cc...c.',
    '.c........c.',
    '.cc......cc.',
    '..cc....cc..',
    '...cccccc...',
    '............',
    '............',
  ],
  maximize: [
    '............',
    '............',
    '.cccccccccc.',
    '.cccccccccc.',
    '.c........c.',
    '.c........c.',
    '.c........c.',
    '.c........c.',
    '.c........c.',
    '.cccccccccc.',
    '............',
    '............',
  ],
  minimize: [
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '............',
    '..cccccccc..',
    '..cccccccc..',
    '............',
    '............',
  ],
  logout: [
    '............',
    '.oooooo.....',
    '.oOOOOo.....',
    '.oOOOOo..c..',
    '.oOOOOo..cc.',
    '.oOOyOcccccc',
    '.oOOOOcccccc',
    '.oOOOOo..cc.',
    '.oOOOOo..c..',
    '.oOOOOo.....',
    '.oooooo.....',
    '............',
  ],
  login: [
    '............',
    '.....oooooo.',
    '.....oOOOOo.',
    '..c..oOOOOo.',
    '..cc.oOOOOo.',
    'cccccoyOOOo.',
    'cccccoOOOOo.',
    '..cc.oOOOOo.',
    '..c..oOOOOo.',
    '.....oOOOOo.',
    '.....oooooo.',
    '............',
  ],

  /* ── Предметы ── */
  msg: [
    '............',
    '.wwwwwwwwww.',
    '.wwwwwwwwww.',
    '.wwgwggwgww.',
    '.wwgwggwgww.',
    '.wwwwwwwwww.',
    '.ssssssssss.',
    '...ww.......',
    '...w........',
    '............',
    '............',
    '............',
  ],
  search: [
    '............',
    '...wwww.....',
    '..wbbbbw....',
    '.wbwbbbbw...',
    '.wbbbbbbw...',
    '.wbbbbbBw...',
    '.wbbbbBBw...',
    '..wBBBBw....',
    '...wwwwoo...',
    '.......ooo..',
    '........oo..',
    '............',
  ],
  settings: [
    '............',
    '.....ww.....',
    '..ww.ww.ww..',
    '..wwwwwwww..',
    '...wwkkws...',
    '.wwwk__kwss.',
    '.wwwk__ksss.',
    '...wskkss...',
    '..wssssss...',
    '..ss.ss.ss..',
    '.....ss.....',
    '............',
  ],
  clock: [
    '............',
    '....yyyy....',
    '..yybbbbyy..',
    '..ybbbybby..',
    '.ybbbyyybby.',
    '.ybbbbybbbY.',
    '.yggggggggY.',
    '.YnnnnnnnnY.',
    '..YnnwnnnY..',
    '..YYnnnnYY..',
    '....YYYY....',
    '............',
  ],
  chest: [
    '............',
    '............',
    '.oooooooooo.',
    '.oooooooooo.',
    '.oooooooooo.',
    '.OOOOssOOOO.',
    '.ooookdoooo.',
    '.oooooooooo.',
    '.oooooooooo.',
    '.oooooooooo.',
    '.OOOOOOOOOO.',
    '............',
  ],
  folder: [
    '............',
    '............',
    '.YYYY.......',
    '.YYYYYYYYYY.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.YYYYYYYYYY.',
    '............',
    '............',
  ],
  trash: [
    '............',
    '....wwww....',
    '.wwwwwwwwww.',
    '.ssssssssss.',
    '............',
    '..wwkwwkww..',
    '..wwkwwkww..',
    '..wwkwwkww..',
    '..wwkwwkww..',
    '..wwkwwkww..',
    '..ssssssss..',
    '............',
  ],
  gem: [
    '............',
    '............',
    '...pprrrr...',
    '..pwprrrRr..',
    '.rrrrrrrrRR.',
    '.Rrrrrrrrrr.',
    '..RrrrrrrR..',
    '...RrrrrR...',
    '....RrrR....',
    '.....RR.....',
    '............',
    '............',
  ],
  shard: [
    '............',
    '.....bb.....',
    '....bwbb....',
    '....bwbb....',
    '...bbwbbB...',
    '...bbbbbB...',
    '...bbbbbB...',
    '...BbbbBB...',
    '....BbbB....',
    '....BBBB....',
    '.....BB.....',
    '............',
  ],
  emerald: [
    '............',
    '.....ll.....',
    '....lwll....',
    '...lwllgl...',
    '..llllllgl..',
    '..lllllggl..',
    '..lllllggl..',
    '..lgllgggl..',
    '...lgggggl..',
    '....lggl....',
    '.....gg.....',
    '............',
  ],
  star: [
    '............',
    '.....yy.....',
    '.....yy.....',
    '....ywyy....',
    '.yyyyyyyyyy.',
    '..yyyyyyyY..',
    '...yyyyyY...',
    '...yyyyyY...',
    '..yyyyyyYY..',
    '..yyy..YYY..',
    '..yy....YY..',
    '............',
  ],
  heart: [
    '............',
    '............',
    '..rrr..rrr..',
    '.rpwrrrrrrr.',
    '.rprrrrrrrr.',
    '.rrrrrrrrRr.',
    '..rrrrrrRR..',
    '...rrrrRR...',
    '....rrRR....',
    '.....RR.....',
    '............',
    '............',
  ],
  'heart-off': [
    '............',
    '............',
    '..www..www..',
    '.wwwwwwwwww.',
    '.wwwwwwwwww.',
    '.wwwwwwwwsw.',
    '..wwwwwwss..',
    '...wwwwss...',
    '....wwss....',
    '.....ss.....',
    '............',
    '............',
  ],
  crown: [
    '............',
    '............',
    '.y...yy...y.',
    '.yy..yy..yy.',
    '.yyy.yy.yyy.',
    '.yyyyyyyyyy.',
    '.yyryybyyly.',
    '.yyyyyyyyyy.',
    '.YYYYYYYYYY.',
    '............',
    '............',
    '............',
  ],
  user: [
    '............',
    '....wwww....',
    '....wwww....',
    '....wwww....',
    '....ssss....',
    '............',
    '..wwwwwwww..',
    '..wwwwwwww..',
    '..wwwwwwww..',
    '..ssssssss..',
    '............',
    '............',
  ],
  users: [
    '............',
    '............',
    '..www..ddd..',
    '..www..ddd..',
    '..sss..ddd..',
    '............',
    '.wwwwwddddd.',
    '.wwwwwddddd.',
    '.wwwwwddddd.',
    '.ssssswnnnn.',
    '............',
    '............',
  ],
  edit: [
    '............',
    '........pp..',
    '.......pppp.',
    '......yyyp..',
    '.....yyyY...',
    '....yyyY....',
    '...yyyY.....',
    '..tyyY......',
    '..ttt.......',
    '..nt........',
    '............',
    '............',
  ],
  lock: [
    '............',
    '....ssss....',
    '...ss__ss...',
    '...s____s...',
    '...s____s...',
    '..yyyyyyyy..',
    '..yyyyyyyy..',
    '..yyykkyyy..',
    '..yyykkyyy..',
    '..yyyyyyyy..',
    '..YYYYYYYY..',
    '............',
  ],
  key: [
    '............',
    '............',
    '............',
    '.yyyy.......',
    '.y__yyyyyyy.',
    '.y__yyyyyyy.',
    '.yyyy..Y.Y..',
    '.......Y.Y..',
    '............',
    '............',
    '............',
    '............',
  ],
  shield: [
    '............',
    '.dddddddddd.',
    '.doooooOOOd.',
    '.dooooooOOd.',
    '.dooooooOOd.',
    '.doooosoOOd.',
    '.dooooooOOd.',
    '..doooooOd..',
    '..dooooOOd..',
    '...dooOOd...',
    '....dddd....',
    '............',
  ],
  bell: [
    '............',
    '.....yy.....',
    '....yyyy....',
    '...ywyyyY...',
    '...ywyyyY...',
    '...yyyyyY...',
    '..yyyyyyYY..',
    '.yyyyyyyyYY.',
    '.YYYYYYYYYY.',
    '.....YY.....',
    '............',
    '............',
  ],
  alert: [
    '............',
    '.....yy.....',
    '....yyyy....',
    '....ykky....',
    '...yykkyy...',
    '...yykkyy...',
    '..yyykkyyy..',
    '..yyyyyyyy..',
    '.yyyykkyyyy.',
    '.YYYYYYYYYY.',
    '............',
    '............',
  ],
  info: [
    '............',
    '..BBBBBBBB..',
    '.BBBBwwBBBB.',
    '.BBBBwwBBBB.',
    '.BBBBBBBBBB.',
    '.BBBwwwBBBB.',
    '.BBBBwwBBBB.',
    '.BBBBwwBBBB.',
    '.BBBBwwBBBB.',
    '.BBBwwwwBBB.',
    '..BBBBBBBB..',
    '............',
  ],
  ban: [
    '............',
    '....rrrr....',
    '..rrrrrrrr..',
    '..rrr__rrr..',
    '.rr__rrr_rr.',
    '.rr__rr__rr.',
    '.rr__rr__rr.',
    '.rr_rrr__rr.',
    '..rrr__rrr..',
    '..rrrrrrrr..',
    '....rrrr....',
    '............',
  ],
  copy: [
    '............',
    '.ssssss.....',
    '.ssssss.....',
    '.ss.wwwwww..',
    '.ss.wwwwww..',
    '.ss.wwwwww..',
    '.ss.wwwwww..',
    '....wwwwww..',
    '....wwwwww..',
    '....wwwwww..',
    '............',
    '............',
  ],
  link: [
    '............',
    '............',
    '......dddd..',
    '.....dd__dd.',
    '.....d____d.',
    '...ssssd__d.',
    '..ss__ssddd.',
    '.s____s.....',
    '.s__ss......',
    '.ssss.......',
    '............',
    '............',
  ],
  eye: [
    '............',
    '............',
    '....llll....',
    '..llllllll..',
    '.lllgkkglll.',
    '.llgkkkkgll.',
    '.llgkkkkgll.',
    '.lllgkkglll.',
    '..llllllll..',
    '....llll....',
    '............',
    '............',
  ],
  brush: [
    '............',
    '.........oo.',
    '........ooo.',
    '.......ooo..',
    '......ooo...',
    '.....sss....',
    '....ssss....',
    '...tttt.....',
    '..ttttt.....',
    '.tttt.......',
    '.tt.........',
    '............',
  ],
  smile: [
    '............',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '.yykyyyykyy.',
    '.yykyyyykyy.',
    '.yyyyyyyyyy.',
    '.ykyyyyyyky.',
    '.yykkkkkkyy.',
    '.yyyyyyyyyy.',
    '.YYYYYYYYYY.',
    '............',
  ],
  thumb: [
    '............',
    '.....cc.....',
    '.....cc.....',
    '....ccc.....',
    '....cccccc..',
    '.cc.ccccccc.',
    '.cc.ccccccc.',
    '.cc.ccccccc.',
    '.cc.ccccccc.',
    '.cc.cccccc..',
    '............',
    '............',
  ],
  sun: [
    '............',
    '.....yy.....',
    '..y..yy..y..',
    '....yyyy....',
    '...yyyyyy...',
    '.yyyyyyyyyy.',
    '.yyyyyyyyyy.',
    '...yyyyyy...',
    '....yyyy....',
    '..y..yy..y..',
    '.....yy.....',
    '............',
  ],
  moon: [
    '............',
    '....ssss....',
    '...ssss.....',
    '..wsss......',
    '..wss.......',
    '..wss.......',
    '..wss.......',
    '..wsss......',
    '...wsss...s.',
    '....wssssss.',
    '.....sssss..',
    '............',
  ],
  monitor: [
    '............',
    '.dddddddddd.',
    '.dbbbbbbbbd.',
    '.dbwbbbbbbd.',
    '.dbbbbbbbbd.',
    '.dbbbbbbbbd.',
    '.dddddddddd.',
    '.....dd.....',
    '...dddddd...',
    '............',
    '............',
    '............',
  ],
  wallet: [
    '............',
    '............',
    '..oooooooo..',
    '.oooooooooo.',
    '.oOOOOOOOOo.',
    '.ooooooyyyy.',
    '.ooooooykyy.',
    '.ooooooyyyy.',
    '.oooooooooo.',
    '.OOOOOOOOOO.',
    '............',
    '............',
  ],
  book: [
    '............',
    '..oooooooo..',
    '..oooooooot.',
    '..ooyyyyoot.',
    '..oooooooot.',
    '..oooooooot.',
    '..oooooooot.',
    '..oooooooot.',
    '..oooooooot.',
    '..Otttttttt.',
    '...OOOOOOOO.',
    '............',
  ],
  image: [
    '............',
    '.oooooooooo.',
    '.obbbbbbbbo.',
    '.obbbwwbbbo.',
    '.obbbbbbbbo.',
    '.obbbbbglbo.',
    '.obgbbglllo.',
    '.ollgllllgo.',
    '.ogllllgggo.',
    '.oooooooooo.',
    '............',
    '............',
  ],
  map: [
    '............',
    '.tttttttttt.',
    '.tllttbbbtt.',
    '.tlllbbbbtt.',
    '.ttlllbbttt.',
    '.ttllltrttt.',
    '.tttlltttt.t',
    '.ttbbllllltt',
    '.tbbbblllltt',
    '.tttttttttt.',
    '............',
    '............',
  ],
  server: [
    '............',
    '.dddddddddd.',
    '.dnnnnnnlld.',
    '.dnnnnnnnnd.',
    '.dddddddddd.',
    '............',
    '.dddddddddd.',
    '.dnnnnnnlld.',
    '.dnnnnnnnnd.',
    '.dddddddddd.',
    '............',
    '............',
  ],
  blocks: [
    '............',
    '.llllllllll.',
    '.llgllllgll.',
    '.gglggglggg.',
    '.ogggoggogo.',
    '.oooooooooo.',
    '.ooOooooOoo.',
    '.oooooOoooo.',
    '.oOoooooooo.',
    '.ooooOoooOo.',
    '.oooooooooo.',
    '............',
  ],
  trophy: [
    '............',
    '..yyyyyyyy..',
    '.yyywyyyyyy.',
    '.y.ywyyyY.y.',
    '.yyyyyyyYyy.',
    '...yyyyyY...',
    '....yyyY....',
    '.....yY.....',
    '.....yY.....',
    '...yyyyYY...',
    '...YYYYYY...',
    '............',
  ],
  zap: [
    '............',
    '......yyy...',
    '.....yyy....',
    '....yyy.....',
    '...yyy......',
    '..yyyyyyy...',
    '.....yyy....',
    '....yyy.....',
    '...yyy......',
    '..yy........',
    '............',
    '............',
  ],
  flame: [
    '............',
    '.....f......',
    '....ff......',
    '....fff..f..',
    '...fffff.f..',
    '..ffffyfff..',
    '..fffyyfff..',
    '..ffyyyyff..',
    '..ffywwyff..',
    '...fywwyf...',
    '....ffff....',
    '............',
  ],
  gift: [
    '............',
    '...rr..rr...',
    '....rrrr....',
    '.wwwwrrwwww.',
    '.wwwwrrwwww.',
    '.ssssrrssss.',
    '..wwwrrwww..',
    '..wwwrrwww..',
    '..wwwrrwww..',
    '..wwwrrwww..',
    '..sssrrsss..',
    '............',
  ],
  hammer: [
    '............',
    '..dddddd....',
    '.dddddddd...',
    '.ddddddddn..',
    '....oo......',
    '....oo......',
    '....oo......',
    '....oo......',
    '....oo......',
    '....OO......',
    '............',
    '............',
  ],
  tap: [
    '............',
    '.c..........',
    '..c.cc......',
    '....wwww....',
    '.c..wwwwww..',
    '....wwwwwww.',
    '....wwwwwww.',
    '....wwwwww..',
    '....wwwwww..',
    '.....sssss..',
    '............',
    '............',
  ],
  sparkle: [
    '............',
    '.....y......',
    '.....y......',
    '....yyy.....',
    '..yyywyyy...',
    '....yyy..w..',
    '.....y..www.',
    '.....y...w..',
    '..w.........',
    '.www........',
    '..w.........',
    '............',
  ],
  // Две ноты вместо пластинки (владелец 24.09.2026: «пластинка непонятна»).
  music: [
    '............',
    '....kkkkkkkk',
    '....kwwwwwwk',
    '....kwkkkkwk',
    '....kwk..kwk',
    '....kwk..kwk',
    '.kkkkwkkkkwk',
    'kwwwwwkwwwwk',
    'kwwwwwkwwwwk',
    '.kkkkk.kkkk.',
    '............',
    '............',
  ],
  mic: [
    '............',
    '....ssss....',
    '....wwws....',
    '....wwws....',
    '....wwws....',
    '..c.ssss.c..',
    '..cc....cc..',
    '...cccccc...',
    '.....cc.....',
    '....cccc....',
    '............',
    '............',
  ],
  cam: [
    '............',
    '............',
    '..........c.',
    '.ddddddd.cc.',
    '.dnnnnnd.cc.',
    '.dnbbbnddcc.',
    '.dnbbbnddcc.',
    '.dnnnnnd.cc.',
    '.ddddddd.cc.',
    '..........c.',
    '............',
    '............',
  ],
  'screen-share': [
    '............',
    '.dddddddddd.',
    '.dbbbccbbbd.',
    '.dbbccccbbd.',
    '.dbbbccbbbd.',
    '.dbbbccbbbd.',
    '.dddddddddd.',
    '.....dd.....',
    '...dddddd...',
    '............',
    '............',
    '............',
  ],
  headset: [
    '............',
    '...ssssss...',
    '..ss....ss..',
    '.ss......ss.',
    '.s........s.',
    '.dd......dd.',
    '.ddd....ddd.',
    '.ddd....ddd.',
    '.ddd....ddd.',
    '.dd......dd.',
    '............',
    '............',
  ],
  volume: [
    '............',
    '............',
    '.....c......',
    '....cc...c..',
    '.cccccc...c.',
    '.cccccc.c.c.',
    '.cccccc.c.c.',
    '.cccccc...c.',
    '....cc...c..',
    '.....c......',
    '............',
    '............',
  ],
  mute: [
    '............',
    '............',
    '.....c......',
    '....cc......',
    '.cccccc.c..c',
    '.cccccc..cc.',
    '.cccccc..cc.',
    '.cccccc.c..c',
    '....cc......',
    '.....c......',
    '............',
    '............',
  ],
  phone: [
    '............',
    '.ccc........',
    '.cccc.......',
    '.cccc.......',
    '..cc........',
    '..ccc.......',
    '...ccc......',
    '....ccc.cc..',
    '.....cccccc.',
    '.......cccc.',
    '........cc..',
    '............',
  ],
  flag: [
    '............',
    '.o.wwwwwwww.',
    '.o.wwwwwwww.',
    '.o.wwrrrrww.',
    '.o.wwrrrrww.',
    '.o.wwwwwwww.',
    '.o.wwwwwwww.',
    '.o.ssssssss.',
    '.o..........',
    '.o..........',
    '.O..........',
    '............',
  ],
  shirt: [
    '............',
    '..bbb..bbb..',
    '.bbbbbbbbbb.',
    '.bbbbbbbbbb.',
    '.bb.bbbb.bb.',
    '....bbbb....',
    '....bbbb....',
    '....bbbb....',
    '....BBBB....',
    '............',
    '............',
    '............',
  ],
  box: [
    '............',
    '............',
    '.oooooooooo.',
    '.oooooooooo.',
    '.oooooooooo.',
    '.OOOOssOOOO.',
    '.ooookdoooo.',
    '.oooooooooo.',
    '.oooooooooo.',
    '.oooooooooo.',
    '.OOOOOOOOOO.',
    '............',
  ],
  inbox: [
    '............',
    '............',
    '.dddddddddd.',
    '.d........d.',
    '.d........d.',
    '.d........d.',
    '.ddd....ddd.',
    '.ddddddddddd',
    '.dddddddddd.',
    '.nnnnnnnnnn.',
    '............',
    '............',
  ],

  /* ── Гардероб: разделы и места на теле ── */
  hat: [
    '............',
    '............',
    '...vvvvvv...',
    '...vvvvvv...',
    '...vvvvvV...',
    '...vvvvvV...',
    '...yyyyyy...',
    '.vvvvvvvvvv.',
    '.VVVVVVVVVV.',
    '............',
    '............',
    '............',
  ],
  glasses: [
    '............',
    '............',
    '............',
    '............',
    '.nnnnnnnnnn.',
    '.nbbnnnnbbn.',
    '.nbbn..nbbn.',
    '.nnnn..nnnn.',
    '............',
    '............',
    '............',
    '............',
  ],
  ear: [
    '............',
    '.w........w.',
    '.ww......ww.',
    '.wpw....wpw.',
    '.wppw..wppw.',
    '.wppwwwwppw.',
    '.wwwwwwwwww.',
    '.wwwwwwwwww.',
    '.wwkwwwwkww.',
    '.wwwwppwwww.',
    '.ssssssssss.',
    '............',
  ],
  backpack: [
    '............',
    '....oooo....',
    '...o....o...',
    '..oooooooo..',
    '..oooooooo..',
    '..OOOyyOOO..',
    '..ooooooooo.',
    '..oooooooo..',
    '..OoooooOo..',
    '..OOOOOOOO..',
    '............',
    '............',
  ],
  wings: [
    '............',
    '.w........w.',
    '.ww......ww.',
    '.www....www.',
    '.wwww..wwww.',
    '.wwwww.wwwww',
    '..swww.wwws.',
    '..ssww.wwss.',
    '...ssw.wss..',
    '....ss.ss...',
    '............',
    '............',
  ],
  cape: [
    '............',
    '..RRRRRRRR..',
    '..rrrrrrrr..',
    '..rrrrrrrr..',
    '..rrrrrrrr..',
    '..rrrrrrrr..',
    '..rrrrrrrr..',
    '..rrrrrrrR..',
    '..rrrrrrrR..',
    '..rRrrRrrR..',
    '............',
    '............',
  ],
  hand: [
    '............',
    '....c.c.....',
    '...cc.c.c...',
    '...cc.c.c...',
    '...cccccc.c.',
    '...cccccc.c.',
    '...ccccccc..',
    '...cccccc...',
    '....cccc....',
    '....cccc....',
    '............',
    '............',
  ],
  shoes: [
    '............',
    '............',
    '............',
    '..oo....oo..',
    '..oo....oo..',
    '..oo....oo..',
    '..oo....oo..',
    '.ooo...ooo..',
    'oooo..oooo..',
    'OOOO..OOOO..',
    '............',
    '............',
  ],
  body: [
    '............',
    '....tttt....',
    '....tttt....',
    '....tttt....',
    '..bbbbbbbb..',
    '..bbbbbbbb..',
    '..bbbbbbbb..',
    '..tBBBBBBt..',
    '....BBBB....',
    '....BBBB....',
    '....nnnn....',
    '............',
  ],
  pants: [
    '............',
    '..BBBBBBBB..',
    '..BBBBBBBB..',
    '..BBBBBBBB..',
    '..BBB..BBB..',
    '..BBB..BBB..',
    '..BBB..BBB..',
    '..BBB..BBB..',
    '..BBB..BBB..',
    '..nnn..nnn..',
    '............',
    '............',
  ],
  paw: [
    '............',
    '..ss....ss..',
    '..ss....ss..',
    '.ss.ss..ss.s',
    '....ss......',
    '...wwwwww...',
    '..wwwwwwww..',
    '..wwwwwwww..',
    '..wwwwwwww..',
    '...ww..ww...',
    '............',
    '............',
  ],
  looks: [
    '............',
    '....oooo....',
    '....oooo....',
    '....oooo....',
    '..oooooooo..',
    '..o.oooo.o..',
    '..o.oooo.o..',
    '....o..o....',
    '....o..o....',
    '...dddddd...',
    '..dddddddd..',
    '............',
  ],
  /* ── Разделы гардероба: одноцветные силуэты 16×16 без контура, как значки
     Essential Mod (правка владельца 23.09.2026). Рисунки свои: исходники
     Essential под лицензией, запрещающей копирование (см. docs/PIXEL-LANGUAGE.md). ── */
  'ws-looks': [
    '................',
    '......cccc......',
    '.....cc..cc.....',
    '.........cc.....',
    '........cc......',
    '.......cc.......',
    '......cccc......',
    '.....cc..cc.....',
    '....cc....cc....',
    '...cc......cc...',
    '..cc........cc..',
    '.cc..........cc.',
    '.cccccccccccccc.',
    '.CCCCCCCCCCCCCC.',
    '................',
    '................',
  ],
  'ws-skin': [
    '.....cccccc.....',
    '.....cccccc.....',
    '.....c_cc_c.....',
    '.....cccccc.....',
    '.....cccccc.....',
    '................',
    '.ccc.cccccc.ccc.',
    '.ccc.cccccc.ccc.',
    '.ccc.cccccc.ccc.',
    '.ccc.cccccc.ccc.',
    '.CCC.cccccc.CCC.',
    '.....cccCCC.....',
    '.....cccCCC.....',
    '.....cccCCC.....',
    '.....cccCCC.....',
    '................',
  ],
  'ws-cape': [
    '................',
    '....CCCCCCCC....',
    '....cccccccc....',
    '....cCcccCcc....',
    '....cCcccCcc....',
    '...ccCcccCccc...',
    '...ccCcccCccc...',
    '...ccCcccCccc...',
    '...ccCcccCccc...',
    '..cccCcccCcccc..',
    '..cccCcccCcccc..',
    '..cccCcccCcccc..',
    '..cccCcccCcccc..',
    '..cccccccccccc..',
    '..cc..cc..cc.c..',
    '................',
  ],
  'ws-head': [
    '................',
    '................',
    '....cccccccc....',
    '....cccccccc....',
    '....cccccccc....',
    '....cccccccc....',
    '....cccccccc....',
    '....cccccccc....',
    '....cccccccc....',
    '....CCCCCCCC....',
    '....CCCCCCCC....',
    '.cccccccccccccc.',
    '.cccccccccccccc.',
    '................',
    '................',
    '................',
  ],
  'ws-body': [
    '................',
    '................',
    '...cccc..cccc...',
    '..cccccccccccc..',
    '.cccccccccccccc.',
    '.cccccccccccccc.',
    '.cccCccccccCccc.',
    '.ccc.cccccc.ccc.',
    '.ccc.cccccc.ccc.',
    '.....cccccc.....',
    '.....cccccc.....',
    '.....cccccc.....',
    '.....cccccc.....',
    '.....CCCCCC.....',
    '................',
    '................',
  ],
  'ws-back': [
    '................',
    '................',
    '.c............c.',
    '.cc..........cc.',
    '.ccc........ccc.',
    '.cccc......cccc.',
    '.ccccc....ccccc.',
    '.cccccc..cccccc.',
    '..ccccc..ccccc..',
    '..CCccc..cccCC..',
    '...CCcc..ccCC...',
    '....CCc..cCC....',
    '.....CC..CC.....',
    '................',
    '................',
    '................',
  ],
  'ws-pet': [
    '................',
    '................',
    '....cc....cc....',
    '...cccc..cccc...',
    '...cccc..cccc...',
    '.cc.cc....cc.cc.',
    'cccc........cccc',
    'cccc..cccc..cccc',
    '.cc..cccccc..cc.',
    '....cccccccc....',
    '...cccccccccc...',
    '...cccccccccc...',
    '...cccccccccc...',
    '....ccc..ccc....',
    '................',
    '................',
  ],
  'ws-emote': [
    '................',
    '................',
    '....cccccccc....',
    '...cccccccccc...',
    '..cccccccccccc..',
    '..ccc__cc__ccc..',
    '..ccc__cc__ccc..',
    '..cccccccccccc..',
    '..cc_cccccc_cc..',
    '..ccc______ccc..',
    '..cccccccccccc..',
    '...cccccccccc...',
    '....cccccccc....',
    '................',
    '................',
    '................',
  ],
}

/* «Выключено»: тот же рисунок, перечёркнутый красной ступенчатой чертой. */
const OFF: Record<string, string> = {
  'phone-off': 'phone',
  'mic-off': 'mic',
  'headset-off': 'headset',
  'music-off': 'music',
}

/* Рисунки, которые повторяют другой: один и тот же предмет у разных id. */
const SAME: Record<string, string> = {
  'box2': 'chest',
  'server-cog': 'server',
  max: 'maximize',
  sticker: 'smile',
  bag: 'emerald',
}

function rot90(a: Art): Art {
  const n = a.length
  return a.map((_, y) => a.map((_, x) => a[n - 1 - x][y]).join(''))
}

function derive(name: string, seen = 0): Art {
  if (OFF[name]) {
    const base = derive(OFF[name], seen + 1).map((r) => r.split(''))
    for (let i = 1; i <= 10; i++) {
      base[i][i] = 'r'
      base[i][i + 1 > 11 ? 11 : i + 1] = 'r'
    }
    return base.map((r) => r.join(''))
  }
  const src = ART[SAME[name] || name]
  if (!src || seen > 4) return ART.dots as Art
  if (Array.isArray(src)) return src
  const base = derive(src.from, seen + 1)
  switch (src.t) {
    case 'flipH':
      return base.map((r) => r.split('').reverse().join(''))
    case 'flipV':
      return [...base].reverse()
    case 'rot90':
      return rot90(base)
    case 'rot180':
      return rot90(rot90(base))
    case 'rot270':
      return rot90(rot90(rot90(base)))
  }
}

export interface PxRect {
  x: number
  y: number
  w: number
  fill: string
  /** Второй тон одноцветного значка. */
  op?: number
}

/** Размер сетки рисунка (12 у значков, 16 у разделов гардероба). */
export function pxSize(name: string): { w: number; h: number } {
  const art = derive(name)
  return { w: art[0].length, h: art.length }
}

/* Без контура: одноцветные значки-действия (крестик, стрелки — только «c»),
   иначе на зелёной кнопке тёмный знак с тёмным контуром сливается в кляксу,
   и разделы гардероба. */
const bare = (name: string, art: Art) => name.startsWith('ws-') || art.every((r) => /^[.c_C ]*$/.test(r))

const OPEN = new Set(['.', '_', ' '])
const cache = new Map<string, PxRect[]>()

/** Прямоугольники рисунка: заливка + достроенный контур, соседние клетки одного цвета слиты в полосы. */
export function pxRects(name: string): PxRect[] {
  const hit = cache.get(name)
  if (hit) return hit
  const art = derive(name)
  const H = art.length
  const W = art[0].length
  const outline = !bare(name, art)
  const cell = (x: number, y: number) => (y < 0 || y >= H || x < 0 || x >= W ? '.' : art[y][x] || '.')
  const grid: string[][] = []
  for (let y = 0; y < H; y++) {
    const row: string[] = []
    for (let x = 0; x < W; x++) {
      const ch = cell(x, y)
      if (ch === '.') {
        const near = [cell(x - 1, y), cell(x + 1, y), cell(x, y - 1), cell(x, y + 1)].some((n) => !OPEN.has(n))
        row.push(near && outline ? 'k' : '.')
      } else row.push(OPEN.has(ch) ? '.' : ch)
    }
    grid.push(row)
  }
  const out: PxRect[] = []
  for (let y = 0; y < H; y++) {
    let x = 0
    while (x < W) {
      const ch = grid[y][x]
      if (ch === '.') {
        x++
        continue
      }
      let e = x + 1
      while (e < W && grid[y][e] === ch) e++
      out.push({ x, y, w: e - x, fill: PX_COLORS[ch] || PX_COLORS.k, op: ch === 'C' ? 0.55 : undefined })
      x = e
    }
  }
  cache.set(name, out)
  return out
}

/** Все имена, у которых есть рисунок. */
export const PX_NAMES: string[] = [...Object.keys(ART), ...Object.keys(SAME), ...Object.keys(OFF)].filter((v, i, a) => a.indexOf(v) === i)

export const hasPx = (name: string) => name in ART || name in SAME || name in OFF
